{{- define "common.container.tpl" -}}
name: {{ .Chart.Name }}
image: "ubuntu:latest"
imagePullPolicy: Always
ports:
  - name: http
    containerPort: 80
resources:
  {{ toYaml .Values.resources | indent 2 }}
{{- end -}}
{{- define "common.container" -}}
  {{- /* clear new line so indentation works correctly */ -}}
{{- println "" -}}
{{- include "tentacle.helpers.merge" (append . "common.container.tpl") | indent 8 -}}
{{- end -}}