{{- define "tentacle.configMap.tpl" -}}
apiVersion: v1
kind: ConfigMap
{{- /*{{ include "tentacle.metadata" (merge . (dict "metadataNameSuffix" "configMap")) }}*/}}
{{ include "tentacle.metadata" . }}
data:
  {{- range $key, $value := .Values.configMap.envs }}
    {{- $key | nindent 2 }}: {{ $value | quote }}
  {{- end -}}

  {{- if .Values.configMap.envFile }}
  APP_CONFIG_FILES: "/app/config/env.yaml"
  env.yaml: |-
    {{- if kindIs "map" .Values.configMap.envFile }}
      {{- toYaml .Values.configMap.envFile | nindent 4 }}
    {{- else }}
      {{- .Values.configMap.envFile | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end -}}

{{- define "tentacle.configMap" -}}
  {{- if .Values.configMap }}
    {{- $tentacleValues := dict "Values" .Values.tentacle -}}
    {{- $overrideValues := dict "Values" (omit .Values "tentacle") -}}
    {{- $noValues := omit . "Values" -}}

    {{- with merge $noValues $overrideValues $tentacleValues }}
      {{- include "tentacle.helpers.merge" (append (list . "configMap") "tentacle.configMap.tpl") }}
    {{- end }}
  {{- end }}
{{- end -}}

{{- define "configMap" -}}
{{- end -}}
