{{- define "tentacle.sealedSecret.tpl" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
{{ include "tentacle.helpers.merge" (append (list . "tentacle.sealedSecret.metadata.tpl") "tentacle.metadata") }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.sealedSecret.data }}
      {{- $key | nindent 4 }}: {{ $value | quote }}
    {{- end -}}
{{- end -}}

{{- define "tentacle.sealedSecret.metadata.tpl" }}
{{- $scope := .Values.sealedSecret.scope | default "strict" -}}

metadata:
  annotations:
    sealedsecrets.bitnami.com/scope: {{ $scope | quote }}
    {{- if not (eq $scope "strict") }}
    sealedsecrets.bitnami.com/{{ $scope }}: "true"
    {{- end -}}
{{- end -}}

{{- define "tentacle.sealedSecret" -}}
  {{- if .Values.sealedSecret }}
    {{- include "tentacle.helpers.merge" (append (list . "sealedSecret") "tentacle.sealedSecret.tpl") }}
  {{- end }}
{{- end -}}

{{- define "sealedSecret" }}
{{- end -}}
