security.require-ssl: true

server:
  ssl:
    enabled: true
    key-store: classpath:keystore/examples-ssl-key.p12
    key-store-password: yg0r2-examples
    key-store-type: PKCS12
  port: 8020

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./build/test;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
