server.port: 8020

spring:
  cache.type: redis
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./build/test;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
  redis:
    host: localhost
    port: 6379
