version: '3.8'

services:
  auth:
    container_name: auth
    depends_on:
      - redis
      - user
    environment:
      - CLIENT_USER_BASEURL=https://host.docker.internal:8020 # Have to use this, because of the generated self signed cert.
#      - CLIENT_USER_BASEURL=https://user:8020
      - SPRING_REDIS_HOST=redis
#    env_file:
#      - ssl-config.env
    image: auth:0.0.1-SNAPSHOT
    ports:
      - 8010:8010
    volumes:
      - keystore-volume:/workspace/BOOT-INF/classes/keystore/:ro

  backend:
    container_name: backend
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
#    env_file:
#      - ssl-config.env
    image: backend:0.0.1-SNAPSHOT
    ports:
      - 8030:8030
    volumes:
      - keystore-volume:/workspace/BOOT-INF/classes/keystore/:ro

  layout:
    container_name: layout
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
#    env_file:
#      - ssl-config.env
    image: layout:0.0.1-SNAPSHOT
    ports:
      - 8000:8000
    volumes:
      - keystore-volume:/workspace/BOOT-INF/classes/keystore/:ro

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
#      - 80:80
      - 443:443
    volumes:
      - type: bind
        read_only: true
        source: ./nginx/conf.d/examples.conf
        target: /etc/nginx/conf.d/default.conf
        volume:
          nocopy: true
      - keystore-volume:/etc/nginx/ssl

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379

  user:
    container_name: user
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
#    env_file:
#      - ssl-config.env
    image: user:0.0.1-SNAPSHOT
    ports:
      - 8020:8020
    volumes:
      - keystore-volume:/workspace/BOOT-INF/classes/keystore/:ro

