version: '3.8'

services:
  auth:
    container_name: auth
    depends_on:
      - redis
      - user
    environment:
      - CLIENT_USER_BASEURL=https://host.docker.internal:8020 # Have to use this, because of the generated self signed cert.
    extends:
      file: _common.yaml
      service: common-ssl-microservice
    image: auth:0.0.1-SNAPSHOT
    ports:
      - 8010:8010

  backend:
    container_name: backend
    depends_on:
      - redis
    extends:
      file: _common.yaml
      service: common-ssl-microservice
    image: backend:0.0.1-SNAPSHOT
    ports:
      - 8030:8030

  user:
    container_name: user
    depends_on:
      - redis
    extends:
      file: _common.yaml
      service: common-ssl-microservice
    image: user:0.0.1-SNAPSHOT
    ports:
      - 8020:8020

