client.user:
  baseUrl: http://user-service.localhost
  endpoint: ${client.user.baseUrl}/api/user/exists

server.port: 8010

spring:
  application.name: auth
  profiles.active:
#    - https
#    - redis
