{{- define "with.tpl" -}}
  {{- $tentacleValues := dict "Values" .Values.tentacle -}}
  {{- $overrideValues := dict "Values" (omit .Values "tentacle") -}}
  {{- $noValues := omit . "Values" -}}

  {{- toYaml (merge $noValues $overrideValues $tentacleValues $) -}}
{{- end -}}

{{- define "with.merge" -}}
  {{- $top := first . -}}
  {{- $overrides := (dict ) -}}

  {{- range (rest .) -}}
    {{- $tpl := dict (include . $top) | default (dict ) }}
    {{- $overrides = (merge $overrides $tpl) -}}
  {{- end -}}

  {{- $overrides -}}
{{- end -}}


---
asd: 123
tentacle: {{ .Values.tentacle.tentacle_key1 }}
{{/*with.tpl:*/}}
{{/*  {{- include "with.tpl" . | nindent 2 }}*/}}
{{/*asdasd:*/}}
{{/*  {{- range $asd := (list (include "with.tpl" .)) }}*/}}
{{/*    {{- print $asd | nindent 2 }}*/}}
{{/*  {{- end }}*/}}
{{/*qweqwe:*/}}
{{/*  {{- with (fromYaml (include "with.tpl" .)) }}*/}}
{{/*    {{- print .Chart.name | nindent 2 }}*/}}
{{/*  {{- end }}*/}}

together:
  cn: {{ .Chart.Name }}
  {{- with (fromYaml (include "with.tpl" .)) -}}
    {{- include "p1" . | nindent 2 }}
{{/*    {{- include "with.merge" (list . "p1" "p2") | nindent 4 }}*/}}
  {{- end -}}

{{/*together2:*/}}
{{/*  {{- with (merge $noValues $overrideValues $tentacleValues) -}}*/}}
{{/*    {{- include "p1" . | nindent 2 }}*/}}
{{/*  {{- end -}}*/}}

{{/*mergedValues:*/}}
{{/*  {{ include "with.tpl" . }}*/}}

{{/*mergedTemplates:*/}}
{{/*  {{- include "with.merge" (list . "p1" "p2") | nindent 2 }}*/}}

{{- define "p1" -}}
data:
  data1: value1
  key: {{ . | quote }}
  chart: {{ .Chart | default "no chart" }}
  chartName: {{ .Chart.Name | default .Chart.name | default "no chart" }}
  values: {{ .Values | default "no values"}}
{{/*  {{ toYaml . }}*/}}
{{/*  releaseName: {{ .Release.Name }}*/}}
{{- end -}}

{{- define "p2" -}}
data:
  data2: value2
{{/*  chartName: {{ .Chart.Name }}*/}}
{{/*  releaseName: {{ .Release.Name }}*/}}
{{- end -}}
