spring:
  datasource:
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE"
    username: "test"
    password: "test"
  jpa:
    #hibernate.ddl-auto: "update"
    #show-sql: true
    properties.hibernate.dialect: "org.hibernate.dialect.H2Dialect"
    #properties.hibernate.format_sql: true

logging.level.org.hibernate:
  SQL: DEBUG
  type: TRACE
