server.port: 8020

spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:./build/test;DB_CLOSE_ON_EXIT=FALSE
#    username: test
#    password: test
  profiles.active:
#    - https
#    - redis
