security.require-ssl: true

server:
  ssl:
    enabled: true
    key-store: classpath:keystore/localhost.p12
    key-store-password:
    key-store-type: PKCS12
  port: 8000

spring:
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
