apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{ template "dummy.labels" $ }} # data simply inserted inline, cannot change indentation
data:
  myValue: "Hello World"
  {{- with .Values.favorite }}
  drink: {{ quote (upper .drink) }}
  {{- if eq .drink "coffee" -}}
    {{ "mug: \"true\"" | nindent 2 }}
  mug-2: "true"
  {{- end }}
  food: {{ .food | upper | quote }}
  multypleDrinks: {{ quote (repeat 5 (printf "%s, " $.Values.favorite.drink)) }}
  multypleFoods: {{ $.Values.favorite.drink | printf "%s, " | repeat 5 | quote }}
  exercise: {{ $.Values.favorite.exercise | default "nope" | quote }}
  {{- end }}
  toppins: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
      {{ $index }}: {{ $topping | title | quote }}
    {{- end }}
  sizes: |-
    {{- range tuple "small" "medium" "large"}}
    - {{ . }}
    {{- end }}
  favorites:
    {{- range $key, $value := .Values.favorite }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{ include "dummy.app" . | indent 2 }}
