apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{ template "dummy.labels" $ }} # data simply inserted inline, cannot change indentation
data:
  myValue: "Hello World"
  {{- with .Values.favorite }}
  drink: {{ quote (upper .drink) }}
  {{- if eq .drink "coffee" -}}
    {{ "mug: \"true\"" | nindent 2 }}
  mug-2: "true"
  {{- end }}
  food: {{ .food | upper | quote }}
  multypleDrinks: {{ quote (repeat 5 (printf "%s, " $.Values.favorite.drink)) }}
  multypleFoods: {{ $.Values.favorite.drink | printf "%s, " | repeat 5 | quote }}
  exercise: {{ $.Values.favorite.exercise | default "nope" | quote }}
  {{- end }}
  toppins: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
    {{ $index }}: {{ $topping | title | quote }}
    {{- end }}
  sizes: |-
    {{- range tuple "small" "medium" "large"}}
    - {{ . }}
    {{- end }}
  favorites: |-
    {{- range $key, $value := .Values.favorite }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{ include "dummy.app" . | indent 2 }}
  iterateWithHardcodedNames: |-
    {{- range tuple "config1.toml" "config2.toml" "config3.toml" }}
    {{ . }}: |-
      {{ $.Files.Get . }}
    {{- end }}
  iterateWithFilesGlob: |-
    {{- range $path, $_ := .Files.Glob "**.toml" }}
    {{ $path }}: |-
      {{ $.Files.Get $path }}
    {{- end }}
  readAsConfig: |-
{{ (.Files.Glob "**.toml").AsConfig | indent 4 }}
  readAsSecret: |-
{{ (.Files.Glob "**.toml").AsSecrets | indent 4 }}
  readByLines:
    {{- range .Files.Lines "foo/bar.txt" }}
    {{ . }}
    {{- end }}
  salad: {{ .Values.global.salad }}
