examples.behemoth: true

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./build/test;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
  jpa.hibernate.ddl-auto: create-drop
#  redis:
#    host: localhost
#    port: 6379
#  session:
#    store-type: redis
