logging.level:
  org.springframework.cloud.gateway: DEBUG
  reactor.netty.http.client: DEBUG

server.port: 80

spring:
  cloud.max-in-memory-size: 524288 # 512 * 1024 byte
  profiles.active: auth,layout,user
